apiVersion: v1
kind: ConfigMap
metadata:
  name: alaitp-api-gateway
data:
  application.yaml: |-
    server:
      port: 8888

    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: job-description-api
              uri: http://job-desc:8815
              predicates:
                - Path=/job-list/**
            # SockJS route
            - id: keyword-sockjs-route
              uri: http://keyword-ws:8816
              predicates:
                - Path=/keyword-ws/info/**
            # Normal Websocket route
            - id: keyword-ws-route
              uri: ws://keyword-ws:8816
              predicates:
                - Path=/keyword-ws/**
    logging:
      level:
        org:
          springframework:
            cloud:
              gateway: debug
