server:
  port: 18888
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8811/eureka'
spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 'http://localhost:3000'
            allowed-methods: '*'
            allowed-headers: '*'
            allow-credentials: true
            max-age: 18000

#spring.cloud.gateway.routes[0].id=keyword-websocket-service
#spring.cloud.gateway.routes[0].uri=lb://keyword-websocket/keyword-ws
#spring.cloud.gateway.routes[0].predicates= Path=/keyword-websocket/keyword-ws/info/**
#spring.cloud.gateway.routes[1].id=keyword-websocket
#spring.cloud.gateway.routes[1].uri=lb:ws://keyword-websocket/keyword-ws
#spring.cloud.gateway.routes[1].predicates= Path=/keyword-websocket/keyword-ws/**


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
