server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8811/eureka'
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: job-description-api
          uri: lb://job-description-api
          predicates:
            - Path=/job-list/**
        - id: co-occurrence-matrix
          uri: lb://matrix
          predicates:
            - Path=/most-correlated-words/**
        - id: internationalization
          uri: lb://internationalization
          predicates:
            - Path=/i18n-content/**
        # SockJS route
        - id: keyword-sockjs-route
          uri: lb://keyword-websocket
          predicates:
            - Path=/keyword-ws/info/**
        # Normal Websocket route
        - id: keyword-ws-route
          uri: lb:ws://keyword-websocket
          predicates:
            - Path=/keyword-ws/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: info
