server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: job-description-api
          uri: http://192.168.49.2:31792
          predicates:
            - Path=/job-list/**
        - id: co-occurrence-matrix
          uri: http://192.168.49.2:31792
          predicates:
            - Path=/most-correlated-words/**
        # SockJS route
        - id: keyword-sockjs-route
          uri: http://192.168.49.2:32486
          predicates:
            - Path=/keyword-ws/info/**
        # Normal Websocket route
        - id: keyword-ws-route
          uri: ws://192.168.49.2:32486
          predicates:
            - Path=/keyword-ws/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug


alaitp:
  frontend:
    uri: http://junpenghe.com,http://www.junpenghe.com,https://junpenghe.com,https://www.junpenghe.com,http://115.159.27.167,http://115.159.27.167:80,http://172.17.0.12,http://172.17.0.12:80,http://com.alaitp.frontend.s3-website.us-east-2.amazonaws.com



