server:
  port: 18888
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8811/eureka'
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
            allowed-headers: "*"
            allow-credentials: true
            max-age: 18000
      routes:
        # SockJS route
        - id: keyword-sockjs-route
          uri: lb://keyword-ws
          predicates:
            - Path=/keyword-ws/info/**
        # Normal Websocket route
        - id: keyword-ws-route
          uri: lb:ws://keyword-ws
          predicates:
            - Path=/keyword-ws/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: info
